Enable mini-benchmark with perf on benchmark runners
We run our benchmarks on dedicated runners by tagging the mini-benchmark job
with `benchmark`. The dedicated benchmark runners are currently m5.12xlarge
instances that only allow 1 job at a time.

diff --git a/.gitlab-ci-common.yml b/.gitlab-ci-common.yml
--- a/.gitlab-ci-common.yml
+++ b/.gitlab-ci-common.yml
@@ -66,6 +66,53 @@ fedora-ninja:
   # override allow failure until https://github.com/MariaDB/server/pull/3026 is merged
   allow_failure: true
 
+mini-benchmark:
+  # We have to re-define script because otherwise, gitlab ci considers this to
+  # be invalid on branches that do not support mini-benchmark
+  script:
+    - ls -la rpm; rm -vf rpm/*.el?.*  # Delete artifacts from Centos builds
+    # Don't use cracklib, otherwise the Sysbench user password will be rejected
+    - rm -vf rpm/*cracklib*.rpm
+    # Nothing provides galera-4 on Fedora, so this step fails if built with wsrep
+    - yum install -y rpm/*.rpm
+    # Fedora does not support running services in Docker (like Debian packages do) so start it manually
+    - /usr/bin/mariadb-install-db -u mysql
+    - sudo -u mysql /usr/sbin/mariadbd & sleep 10
+    # Since we did a manual start, we also need to run upgrade manually
+    - /usr/bin/mariadb-upgrade -u root
+    - |
+      mariadb --skip-column-names -e "SELECT @@version, @@version_comment" | tee /tmp/version
+      grep $MARIADB_MAJOR_VERSION /tmp/version || echo "MariaDB didn't install properly"
+    - yum install -y sysbench procps-ng perf flamegraph flamegraph-stackcollapse-perf util-linux dnf-utils
+    - |
+      if [[ "${MARIADB_MAJOR_VERSION}" =~ 10\..* ]]; then
+        /usr/share/mysql/mini-benchmark --perf 
+      fi
+    - |
+      if [[ "${MARIADB_MAJOR_VERSION}" =~ 11\..* ]]; then
+        /usr/share/mariadb/mini-benchmark --perf 
+      fi
+    - cp -av */sysbench-run-*.log */metrics.txt .  # Move files one level down so they can be saved as artifacts
+  tags:
+    - benchmark
+  # Can't use rules:exists:'support-files/mini-benchmark.sh' because it will search for the file in this `gitlab-ci` branch
+  # We can use rules:exists once this issue is fixed https://gitlab.com/gitlab-org/gitlab/-/issues/386040.
+  rules:
+    - if: $MARIADB_MAJOR_VERSION && $MARIADB_MAJOR_VERSION != "10.4" && $MARIADB_MAJOR_VERSION != "10.5" && $MARIADB_MAJOR_VERSION != "10.6"
+# # This is not yet implemented, but a placeholder and example of what can be done with internal CI.
+#   after_script:
+#     - mkdir -p plots
+#     # - ./parse_results.py  # Do additional analysis of reported results
+#   artifacts:
+#     when: always
+#     paths:
+#       - sysbench-run-*.log
+#       # extend artifats with additional plots directory
+#       - plots/
+#     reports:
+#       metrics:
+#         - metrics.txt
+
 # Sast scanning is a mess when trying to maintain an ignorelist across all branches.
 # Let's allow failure until it can be properly cleaned up
 cppcheck:
